#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


#!/ Frontend 
echo "Running frontend linting tool..🥯🥯🥯"
cd ./frontend && npm run lint:fix && npm run format 
echo "\033c"


#!/ Backend 
echo "Running web3/backend linting tool..🍣🍣🍣"
cd ../web3 && npm run prettier:solidity   
echo "\033c"
